apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flaski
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: master
    http:
      paths:
      - path: /
        backend:
          serviceName: flaskiservice
          servicePort: http
